# Custom training arguments
tokenizer: "HuggingFaceTB/SmolLM2-1.7B"
xlstm_config_path: "./model_config.yaml"
features: ["tweet"]

dataset_url: "HausaNLP/AfriSenti-Twitter"
train_subset: "hau"
train_split: "train"
train_samples: 20000

eval_subset: "hau"
eval_split: "test"
eval_samples: 5000

# HF TrainerArguments arguments
num_train_epochs: 5
gradient_accumulation_steps: 10
per_device_train_batch_size: 5
per_device_eval_batch_size: 5

# optim args
learning_rate: 0.0002
weight_decay: 0.001
warmup_ratio: 0.1
optim: "adamw_torch"
lr_scheduler_type: "cosine"
torch_compile: false
fp16: false
use_cpu: false
gradient_checkpointing: false

output_dir: "artifacts"
logging_dir: "artifacts"
report_to: "tensorboard"
logging_steps: 200
save_steps: 200
hub_private_repo: false
save_total_limit: 2
load_best_model_at_end: true
eval_strategy: "steps"

push_to_hub: true
resume_from_checkpoint: "artifacts"
hub_model_id: "thiomajid/hausa_lm"
remove_unused_columns: false
