- hub_id: "CohereLabs/aya_dataset"
  split: "train"
  subset: "default"
  samples: "all"
  text_column: "inputs"
  filter_rules: 
    - lhs: "language"
      op: "eq"
      rhs: "Hausa"


- hub_id: "CohereLabs/aya_dataset"
  split: "train"
  subset: "default"
  samples: "all"
  text_column: "targets"
  filter_rules: 
    - lhs: "language"
      op: "eq"
      rhs: "Hausa"


- hub_id: "CohereLabs/aya_dataset"
  split: "test"
  subset: "default"
  samples: "all"
  text_column: "inputs"
  filter_rules: 
    - lhs: "language"
      op: "eq"
      rhs: "Hausa"

- hub_id: "CohereLabs/aya_dataset"
  split: "train"
  subset: "default"
  samples: "all"
  text_column: "targets"
  filter_rules: 
    - lhs: "language"
      op: "eq"
      rhs: "Hausa"
      