defaults:
  - _self_

base_tokenizer: "HuggingFaceTB/SmolLM2-135M"
vocab_size: 49152

# Dataset configuration  
dataset_url: "thiomajid/base_hausa_datamix"
text_column: "text"
split: "train"
subset: null
samples: "all" 

# Training configuration
batch_size: 1000
output_dir: "./trained_tokenizer"

model_id: "thiomajid/hausa_lm"
hub_token: ""
trust_remote_code: true
